### ISSUE TITLE
Router

### ISSUE THREAD

**Issue by pvseydlitz** [pvseydlitz/capstone-project#16]
## Value statement - a requirement, not a solution
As a user
I need to be able to switch between different content-sides of the app
so that different al functions of the app are accessible. 
## Acceptance criteria
- [ ] when clicked on the icon switch to a different side
## Tasks
- [ ] install router
- [ ] implement router to app
- [ ] test it on mobile
## Size
small
