### ISSUE TITLE
Form

### ISSUE THREAD

**Issue by pvseydlitz** [pvseydlitz/capstone-project#17]
## Value statement - a requirement, not a solution
As a user 
I need a form
so that I can add content to the homepage
## Description (Text, Scribble, Wireframe, Design)
form should have all input boxes like on the example below
![image](https://user-images.githubusercontent.com/56016273/69920414-09c16b00-1488-11ea-9bc6-fce3a4ad904e.png)

## Acceptance criteria
- [ ] form with all input fields is visible on the second page
## Tasks
- [ ] create new form component
- [ ] add all input fields and checkboxes
- [ ] style them like on the sketch template
## Size
large
