### ISSUE TITLE
content of messages

### ISSUE THREAD

**Issue by pvseydlitz** [pvseydlitz/capstone-project#18]
## Value statement - a requirement, not a solution
As a user
I need to see messages on the home screen
so that I know what is going on in the house
## Acceptance criteria
- [ ] All content form the form should be visible in one messages
## Tasks
- [ ] change cards.json so that all inputs can be saved there
- [ ] work out a good and structured layout for the messages
## Size
medium
