### ISSUE TITLE
Add messages

### ISSUE THREAD

**Issue by pvseydlitz** [pvseydlitz/capstone-project#19]
## Value statement - a requirement, not a solution
As a user
I need an option to add messages to the home screen
so that these messages are accessible for all users
## Acceptance criteria
- [ ] content typed in the form appears on the home screen
## Tasks
- [ ] add local storage
- [ ] save input to local storage
- [ ] make them visible on home screen
## Size
(small, medium, large)
