### ISSUE TITLE
add first feature

### ISSUE THREAD

**Issue by pvseydlitz** [pvseydlitz/capstone-project#2]
## Value statement - a requirement, not a solution
As a user 
I need to have a show more button
so that I can see the whole content of the card
## Description (Text, Scribble, Wireframe, Design)
show more / show less button
## Acceptance criteria
- [ ] fold and unfold card
- [ ] styling like on the sketch template
- [ ] text in button changes
## Tasks
- [ ] create button component
- [ ] style and position it
- [ ] make card fold and unfold
- [ ] test it on mobile
## Size
medium
