### ISSUE TITLE
delete-messages

### ISSUE THREAD

**Issue by pvseydlitz** [pvseydlitz/capstone-project#27]
## Value statement - a requirement, not a solution
As a user 
I need a button 
so that I can delete certain messages
## Acceptance criteria
- [ ] message disappears from the home screen
- [x] message is deleted form the server
## Tasks
- [ ] add a cross symbol to every message
- [x] implement delete function for server
- [x] build up an alert so that delete has to be confirmed
## Size
medium
