### ISSUE TITLE
Form2

### ISSUE THREAD

**Issue by pvseydlitz** [pvseydlitz/capstone-project#28]
## Value statement - a requirement, not a solution
As a user
I need a second form  
so that another category of message can be added
## Acceptance criteria
- [ ] second form für TÜV-Mängel can be selected
## Tasks
- [ ] build up a second form
- [x] add a dropdown menu to make a selection between both forms
- [x] add a new collection to the mongo db
- [x] implement post method for these messages
## Size
medium
