### ISSUE TITLE
Display-message2

### ISSUE THREAD

**Issue by pvseydlitz** [pvseydlitz/capstone-project#29]
## Value statement - a requirement, not a solution
As a user
I need to see both messages on the home screen
## Acceptance criteria
- [ ] TÜV-Mängel are displayed on the home screen
## Tasks
- [ ] add a menu to switch between both categories of messages
- [x] implement get method from the server
- [x] build up a search function to search for certain TÜV-Mängel
## Size
large
