### ISSUE TITLE
Upload Images

### ISSUE THREAD

**Issue by pvseydlitz** [pvseydlitz/capstone-project#31]
## Value statement - a requirement, not a solution
As a user
I need to upload images
so that the damage is visible for everyone. 
## Acceptance criteria
- [ ] pictures can be uploaded and are visible on the message
## Tasks
- [ ] install cloudinary
- [ ] implement upload methode
- [ ] safe url of each image on the server
- [ ] place image under the content of every message
## Size
large
