### ISSUE TITLE
filter logic

### ISSUE THREAD

**Issue by pvseydlitz** [pvseydlitz/capstone-project#5]
## Value statement - a requirement, not a solution
As a user
I need a filter button
so that I can sort the cards by certain criteria
## Description (Text, Scribble, Wireframe, Design)
criteria: bookmarked, category of card
## Acceptance criteria
- [ ] only cards that comply with filter categories are shown 
## Tasks
- [ ] add dropdown menu that appears when clicked on the filter button
- [ ] add state onlyCardsShown
## Size
large
