### ISSUE TITLE
messages.json

### ISSUE THREAD

**Issue by pvseydlitz** [pvseydlitz/capstone-project#7]
## Value statement - a requirement, not a solution
As a user
I need to see many messages on the home screen
so that all relevant infos are displayed. 
## Description (Text, Scribble, Wireframe, Design)
messages with the same layout are displayed on the home screen 
## Acceptance criteria
- [ ] content from messages.json visible
## Tasks
- [ ] create messages.json
- [ ] fill 3 objects with content
## Size
medium
